#!/bin/sh
### BEGIN INIT INFO
# Provides: {{ service_name }}
# Required-Start: $local_fs $network $named $time $syslog docker
# Required-Stop: $local_fs $network $named $time $syslog docker
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: <DESCRIPTION>
### END INIT INFO

SHARED_DIR="{{ deploy_root }}/shared"
DEPLOY_DIR="{{ deploy_root }}/releases/{{ docker_tag }}"
PROJECT="{{ project_name }}"

ENV_FILE="${SHARED_DIR}/make_env.sh"
COMPOSE="${DEPLOY_DIR}/docker-compose.yml"

CMDBASE=". ${ENV_FILE} ; docker-compose -f $COMPOSE -p $PROJECT"
START="${CMDBASE} up -d"
STOP="${CMDBASE} stop"

RUNAS=root

start() {
echo 'Starting service…' >&2
echo "$START" >&2
su -c "$START" $RUNAS
echo 'Service started' >&2
}

stop() {
echo 'Stopping service…' >&2
su -c "$STOP" $RUNAS
echo 'Service stopped' >&2
}

status() {
docker ps | grep $PROJECT
}

# this does not remove running containers
remove_containers() {
docker rm {{ service_name }}_mysql {{ service_name }}_apache {{ service_name }}_ambassador
}

case "$1" in
status)
status
;;
start)
start
;;
stop)
stop
;;
restart)
stop
start
;;
remove_containers)
remove_containers
;;
*)
echo "Usage: $0 {start|stop|restart|status|remove_containers}"
esac
