ambassador:
  image: cpuguy83/docker-grand-ambassador
  container_name: {{ service_name }}_ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name {{ service_name }}_mysql -name {{ service_name }}_apache"

mysql:
  image: {{ docker_owner }}/booked-mysql:{{ docker_tag }}
  container_name: {{ service_name }}_mysql
  environment:
    MYSQL_ROOT_PASSWORD:
    MYSQL_USER: "booked_user"
    MYSQL_PASSWORD:
    MYSQL_DATABASE: "bookedscheduler"
  links:
   - "ambassador:web"
  volumes:
   - "/etc/localtime:/etc/localtime"

apache:
  image: {{ docker_owner }}/booked-apache:{{ docker_tag }}
  container_name: {{ service_name }}_apache
  ports:
   - "443:443"
  environment:
    MYSQL_PASSWORD:
    BOOKED_RECAPTCHA_SITE_KEY:
    BOOKED_RECAPTCHA_SECRET_KEY:
    BOOKED_ADMIN_EMAIL: {{ booked_admin_email }}
    DOCKER_HOST: {{ docker_host }}
  links:
   - "ambassador:mysql"
  volumes:
   - "/etc/localtime:/etc/localtime"
   - {{ docker_host_certificate }}:/etc/pki/tls/certs/docker-host-certificate.pem
   - {{ docker_host_key }}:/etc/pki/tls/private/docker-host.key
   - {{ ocf_export_dir }}:/ocf_export
